# 메뉴 생성
PUT http://localhost:8080/v1/menu
Content-Type: application/json

[
  {
    "categoryId": 1,
    "menuName": "메뉴1",
    "menuPrice":  1500
  },
  {
    "categoryId": 1,
    "menuName": "메뉴2",
    "menuPrice":  0
  }
]
