drop table if exists authority cascade;
drop table if exists category cascade;
drop table if exists member cascade;
drop table if exists menu cascade;
drop table if exists option cascade;
drop table if exists sub_option cascade;

create table authority (
    id bigint generated by default as identity,
    description varchar(30) default NULL,
    name varchar(30) not null unique,
    primary key (id)
);

create table category (
    id bigint generated by default as identity,
    parent bigint,
    name varchar(50) not null unique,
    primary key (id)
);

create table member (
    authority_id bigint,
    create_date timestamp(6) not null,
    id bigint generated by default as identity,
    update_date timestamp(6) not null,
    username varchar(20) not null unique,
    name varchar(50) not null,
    nickname varchar(50) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    primary key (id)
);

create table menu (
    available boolean not null,
    category_id bigint,
    id bigint generated by default as identity,
    price bigint not null,
    name varchar(50) not null unique,
    primary key (id)
);

create table option (
    display_order integer not null,
    category_id bigint,
    id bigint generated by default as identity,
    menu_id bigint,
    name varchar(255) not null unique,
    type varchar(255) not null check (type in ('CATEGORY','MENU')),
    primary key (id)
);

create table sub_option (
    display_order integer not null,
    id bigint generated by default as identity,
    option_id bigint,
    price bigint not null,
    name varchar(255) not null unique,
    primary key (id)
);

alter table if exists category
    add constraint FK_CATEGORY_PARENT_CATEGORY_ID
        foreign key (parent) references category;

alter table if exists member
    add constraint FK_MEMBER_AUTHORITY_ID_AUTHORITY_ID
        foreign key (authority_id) references authority;

alter table if exists menu
    add constraint FK_MENU_CATEGORY_ID_CATEGORY_ID
        foreign key (category_id) references category;

alter table if exists option
    add constraint FK_OPTION_CATEGORY_ID_CATEGORY_ID
        foreign key (category_id) references category;

alter table if exists option
    add constraint FK_OPTION_MENU_ID_MENU_ID
        foreign key (menu_id) references menu;

alter table if exists sub_option
    add constraint FK_SUB_OPTION_OPTION_ID_OPTION_ID
        foreign key (option_id) references option;