crypto:
  aes:
    secret: local

jwt:
  issuer: devh
  secret: local
  expire:
    access: 86400 # 1day
    refresh: 3600 # 1hour
  header: Authorization
  cookie:
    access: a-key
    refresh: r-key
