spring:
  application:
    name: menu-api
  config:
    activate:
      on-profile: production
    import:
      - application-infrastructure-database-production.yml
      - application-utility-production.yml

server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
