spring:
  application:
    name: menu-api
  config:
    activate:
      on-profile: test
    import:
      - application-infrastructure-database-test.yml
      - application-utility-test.yml

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
