spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: false
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
